name: CI/CD on push of lightweight tag to main branch

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  ship:
    if: github.event.base_ref == 'refs/heads/main'
    environment:
      name: Documentation
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure CMake for test executable
      run: mkdir -p ./build/cmake && cmake -DBUILD_TYPE="testing" -S . -B ./build/cmake/
    - name: Build test executable
      run: cmake --build ./build/cmake/
    - name: Run tests
      run: ./build/cmake/rubber_numbers
    - name: Install Doxygen
      run: sudo apt update && sudo apt install -y doxygen
    - name: Build docs
      run: mkdir -p build/doxygen && doxygen Doxyfile
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './build/doxygen/html'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
    - name: Clear build files
      run: rm -rf ./build
    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        body: See CHANGELOG.md for this version's changes.
        

