name: CI/CD on tagged push to main branch

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure CMake for test executable
      run: mkdir -p ./build/cmake && cmake -DBUILD_TYPE="testing" -S . -B ./build/cmake/
    - name: Build test executable
      run: cmake --build ./build/cmake/
    - name: Run tests
      run: ./build/cmake/rubber_numbers
    - name: Configure CMake for release libraries
      run: cmake -DBUILD_TYPE="release" -S . -B ./build/cmake/
    - name: Clear build files
      run: rm -rf ./build
    - name: Create release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_name: Release ${{ github.ref }}
        tag_name: ${{ github.ref }}
        body: |
          "See CHANGELOG.md for this version's changes."
        draft: false
        prerelease: false
      
